version: '3.8'
services:
  postgres:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - api
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    env_file:
      - docker.env
    build:
      context: .
      dockerfile: Dockerfile
    image: taskviewer-api:latest
    ports:
      - "8080:8080"
    networks:
      - api
    depends_on:
      - postgres
volumes:
  postgres:
    driver: local
networks:
  api:
    driver: bridge