spring:
  application:
    name: task-viewer-api
  config:
    import: optional:.env[.properties]
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/postgres
server:
  shutdown: graceful
logging:
  level:
    com.solvd.mbook: ${APP_LOG_LEVEL}
    org.springframework.jdbc: ${JDBC_LOG_LEVEL}
    web: ${WEB_LOG_LEVEL}
  file:
    path: /
    name: api.log
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /system