name: maven
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: |
          export POSTGRES_USER=user
          export POSTGRES_PASSWORD=password
          export POSTGRES_HOST=localhost
          export JDBC_LOG_LEVEL=DEBUG
          export WEB_LOG_LEVEL=DEBUG
          export APP_LOG_LEVEL=DEBUG
          mvn clean install --errors --batch-mode